version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./redis/conf:/usr/local/etc/redis
      - ./data/redis:/data
