services:
  easytier:
    image: easytier/easytier:latest
    command: ${COMMAND:-}
    restart: always
    privileged: true
    hostname: ${HOSTNAME}
    network_mode: host
    environment:
    - TZ=Asia/Shanghai
volumes:
  home: