# https://docs.gitlab.com/omnibus/docker/
version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://0.0.0.0'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        letsencrypt['enable'] = false
        nginx['listen_https'] = false
        nginx['enable'] = false
        nginx['listen_port'] = 80
        puma['listen'] = '0.0.0.0
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
