services:
  editor:
    image: apiv1/myvim
    working_dir: /app
    volumes:
      - home:/root
      - .:/app
    tmpfs:
      - /root/.ssh
    configs:
      - source: .gitconfig
        target: /root/.gitconfig
      - source: .bash_aliases
        target: /root/.bash_aliases
    environment:
      - LC_ALL=C.UTF-8
configs:
  .bash_aliases:
      content: |
        test -f ./Shell/richrc && source ./Shell/richrc
        test -d .ssh && cp -R .ssh/* /root/.ssh/ && chmod -R 400 /root/.ssh/
        export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        myvim_install () {
          git clone https://github.com/myvim/.vim ~/.vim
        }
        myself_install() {
          test -d .git && echo 'already installed' && return 1
          git clone --no-checkout https://github.com/apiv1/apiv1.github.io /tmp/apiv1/apiv1.github.io
          mv /tmp/apiv1/apiv1.github.io/.git .
          git reset --hard HEAD
        }
  .gitconfig:
      content: |
        [safe]
          directory = *
        [credential]
          helper = store
        [url "https://kkgithub.com/"]
          insteadOf = https://github.com/
        [url "git@github.com:"]
          pushInsteadOf = https://github.com/
volumes:
  home:
