name: myenv
services:
  editor:
    image: apiv1/myvim
    network_mode: ${NETWORK_MODE:-default}
    working_dir: ${PATH_PREFIX:-}${WORKING_DIR:-/workdir}
    volumes:
      - home:/root
      - .:${PATH_PREFIX:-}${WORKING_DIR:-/workdir}
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    tmpfs:
      - /root/.ssh
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
volumes:
  home:
