name: myvim
services:
  editor:
    image: apiv1/myvim
    network_mode: ${NETWORK_MODE:-default}
    working_dir: ${PATH_PREFIX:-}${PWD}
    volumes:
      - home:/root
      - .:${PATH_PREFIX:-}${PWD}
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    tmpfs:
      - /root/.ssh
    configs:
      - source: .gitconfig
        target: /root/.gitconfig
      - source: .bash_aliases
        target: /root/.bash_aliases
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
configs:
  .bash_aliases:
    content: |
      export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      export PATH=~/.bin:"$$PATH"
      load_local_ssh_keys() {
        test -d .ssh && cp -R .ssh/* /root/.ssh/ && chmod -R 400 /root/.ssh/
        test -d .ssh.enc && mkdir -p /root/.ssh.enc/ && cp -R .ssh.enc/* /root/.ssh.enc/
      }
      unload_ssh_keys() {
        rm -rf ~/.ssh/*
        unset AES_KEY
      }
      ssh_keys_decrypt() {
        echo "decrypt: ~/.ssh.enc => ~/.ssh"
        test -d ~/.ssh.enc || return 1
        test -z $$AES_KEY && echo -n 'password: ' && read -s AES_KEY && export AES_KEY && echo
        for item in `ls ~/.ssh.enc`
        do
          cat ~/.ssh.enc/$$item | base64 -d | aes -d > ~/.ssh/$$item
          chmod 400 ~/.ssh/$$item
          echo "decrypt: ~/.ssh.enc/$$item => ~/.ssh/$$item"
        done
      }
      ssh_keys_encrypt() {
        echo "encrypt: ~/.ssh => ~/.ssh.enc"
        test -z $$AES_KEY && echo -n 'password: ' && read -s AES_KEY && export AES_KEY && echo
        mkdir -p ~/.ssh.enc
        for item in `ls ~/.ssh`
        do
          cat ~/.ssh/$$item | aes -e | base64 -w 0 > ~/.ssh.enc/$$item
          echo "encrypt: ~/.ssh/$$item => ~/.ssh.enc/$$item"
        done
      }
      ssh_keys_install () {
        git clone https://github.com/apiv1/.ssh.enc ~/.ssh.enc
      }
      myvim_install () {
        git clone https://github.com/myvim/.vim ~/.vim
      }
      mybook_install_here() {
        test -d .git && echo 'already installed' && return 1
        git clone --no-checkout https://github.com/apiv1/apiv1.github.io /tmp/apiv1/apiv1.github.io
        mv /tmp/apiv1/apiv1.github.io/.git .
        git reset --hard HEAD
      }
      load_envs() {
        cd ~/.envrc.d >/dev/null 2>&1 || return 1
        for item in `ls -A 2>/dev/null`
        do
          . $$item
        done
        cd - >/dev/null 2>&1
      }
      load_envs
  .gitconfig:
    content: |
      [safe]
        directory = *
      [credential]
        helper = store
      [url "https://kkgithub.com/"]
        insteadOf = https://github.com/
      [url "ssh://git@ssh.github.com:443/"]
        pushInsteadOf = https://github.com/
      [url "ssh://git@ssh.github.com:443/"]
        insteadOf = git@github.com:
volumes:
  home:
