services:
  registry:
    image: registry:2.8.3
    ports:
      - 5000:5000
    restart: always
    volumes:
      - data:/var/lib/registry
      - auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  mirror:
    image: registry:2.8.3
    ports:
      - 5001:5000
    restart: always
    volumes:
      - data:/var/lib/registry
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
volumes:
  auth:
  data:
