services:
  mirror:
    image: registry:2.8.3
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./data:/var/lib/registry
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io

# daemon.json
#{
#  insecure-registries": ["<ip>:5000"],
#  registry-mirrors": ["http://<ip>:5000"]
#}