version: '3'
services:
  cache:
    image: registry:2.7.1
    ports:
      - 5000:5000
    restart: always
    volumes:
      - data:/var/lib/registry
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry.docker-cn.com
  mirror:
    image: registry:2.7.1
    ports:
      - 5001:5000
    restart: always
    volumes:
      - mirror:/var/lib/registry
volumes:
  data:
  mirror:
