version: '3'
services:
  registry:
    image: registry:2.7.1
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

# add user:
# mkdir ./auth; docker run --entrypoint htpasswd httpd:2 -Bbn testuser testpassword > ./auth/htpasswd
