version: '3'
services:
  app:
    build: .
    command: jupyter lab --allow-root --ip 0.0.0.0
    restart: always
    volumes:
      - "./jupyter.config.d:/root/.jupyter"
      - "./workdir:/workdir"
      - "site-packages:/usr/local/lib/python2.7/site-packages"
    ports:
      - "127.0.0.1:52134:8888"
volumes:
  site-packages: