version: '3'
services:
  app:
    image: gitea/gitea:1.19
    volumes:
      - ./docker/app/data:/data
    ports:
      - "30000:30000"
      - "2200:22"
    depends_on:
      - db
    restart: always
    environment:
      - SSH_PORT=2200
      - HTTP_PORT=30000

      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea

      - DISABLE_REGISTRATION=true
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./docker/db:/var/lib/postgresql/data
