name: dood-sshd
services:
  dood:
    image: apiv1/sshd:docker
    init: true
    entrypoint: sh
    command: |
      -c '
        groupadd --gid $${PGID} $${USERNAME}
        useradd --shell /bin/sh --uid $${PUID} --gid $${PGID} --password $$(openssl passwd $${PASSWORD}) --create-home --home-dir /home/$${USERNAME} $${USERNAME}
        usermod -aG docker $${USERNAME}

        chown -R $${USERNAME}:$${USERNAME} /home/$${USERNAME}
        chown -R $${USERNAME}:$${USERNAME} /var/run/docker.sock
        chmod 400 /home/$${USERNAME}/.ssh/authorized_keys
        exec /entrypoint.sh
      '
    environment:
      - PUID=${PUID:-2000}
      - PGID=${PGID:-2000}
      - USERNAME=${USERNAME:-docker}
      - PASSWORD=${PASSWORD:-passwd654321!}
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:rw
      - ssh:/etc/ssh
    restart: always
volumes:
  ssh: