name: k3s
services:
  k3s:
    image: rancher/k3s
    command: server ${SERVICE_ARGS:-""} --disable traefik
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - data:/var/lib
      - config:/etc/rancher
    configs:
      - source: registries.yaml
        target: /etc/rancher/k3s/registries.yaml
volumes:
  data:
  config:
configs:
  registries.yaml:
    content: |
      ${REGISTRY_CONFIG}