services:
  nacos:
    image: apiv1/nacos
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - nacos-data:/nacos/data
      - nacos-logs:/nacos/log
    restart: always
volumes:
  nacos-data:
  nacos-logs: