services:
  client:
    image: v2fly/v2fly-core
    restart: always
    ports:
      - "127.0.0.1:1080:1080"
    volumes:
      - ./config.client.json:/etc/v2ray/config.json
  server:
    image: v2fly/v2fly-core
    restart: always
    ports:
      - "32767:32767"
    volumes:
      - ./config.server.json:/etc/v2ray/config.json