---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ip-echo
  name: ip-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ip-echo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ip-echo
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - args:
            - :8089
          image: apiv1/ip-echo
          name: ip-echo
          ports:
            - containerPort: 8089
          resources: {}
          env:
            - name: TOKEN
              value: ''
      restartPolicy: Always
status: {}