version: '3'
services:
  runner:
    image: gitlab/gitlab-runner:alpine-v13.12.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/config:/etc/gitlab-runner
