services:
  java:
    build:
      context: .
      dockerfile_inline: |
        FROM openjdk:8-jre-slim
        ENV TZ=PRC
        RUN ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime && echo $$TZ > /etc/timezone

        COPY target/*.jar /app.jar
    command: |
      java -jar /app.jar