# docker run -d --name nfs-server --privileged --restart always -p 2049:2049 -v /mnt/data-disk-1/nfs/nfs-share:/nfs-share -e SHARED_DIRECTORY=/nfs-share itsthenetwork/nfs-server-alpine:latest
version: '3'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine
    privileged: true
    ports:
      - 2049:2049
    volumes:
      - ./nfs-share:/nfs-share
    environment:
      SHARED_DIRECTORY: /nfs-share

