services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sql@1433
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
