version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
      - STAGING
      - DHPARAM_SIZE
      - RSA_KEY_SIZE
      - RENEWAL_INTERVAL
      - DEBUG
    network_mode: host
    volumes:
      - ./nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

