version: '3'
services:
  samba:
    image: dperson/samba
    command: -w "WORKGROUP" -u "user;user@2020123" -s "user;/mount;yes;no;no;user;user;user"
    restart: always
    volumes:
      - ./mount:/mount
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
