
services:
  gerrit:
    image: gerritcodereview/gerrit:3.0.0
    ports:
      - "29418:29418"
      - "8080:8080"
    depends_on:
      - ldap
    volumes:
      - ./gerrit/etc:/var/gerrit/etc
      - ./gerrit/git:/var/gerrit/git
      - ./gerrit/db:/var/gerrit/db
      - ./gerrit/index:/var/gerrit/index
      - ./gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://0.0.0.0
    # entrypoint: /entrypoint.sh init

  ldap:
    image: osixia/openldap:1.2.4
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - ./gerrit/ldap/var:/var/lib/ldap
      - ./gerrit/ldap/etc:/etc/ldap/slapd.d

  ldap-admin:
    image: osixia/phpldapadmin:0.8.0
    depends_on:
      - ldap
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap