version: "3.1"
services:
  db:
    image: mongo:4.0.14-xenial
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_321_654
    volumes:
      - db:/data/db
volumes:
  db: