name: sshd
services:
  sshd:
    image: linuxserver/openssh-server
    ports:
      - "2222:2222"
    environment:
      - LISTEN_PORT=${LISTEN_PORT:-2222}
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
      - USER_NAME=username
      - PUBLIC_KEY_DIR=/public/.ssh
    volumes:
      - ./.storage:/storage
      - ssh:/public/.ssh/
      - logs:/config/logs
volumes:
  ssh:
  logs: