name: sshd-dood
services:
  sshd:
    build:
      dockerfile_inline: |
        FROM linuxserver/openssh-server
        COPY --from=apiv1/docker /docker /usr/local/sbin/
    command: |
      sudo sh -c '
        chown docker:docker /var/run/docker.sock
        sleep infinity
      '
    ports:
      - "2222:2222"
    environment:
      - LISTEN_PORT=2222
      - SUDO_ACCESS=true
      - USER_NAME=docker
      - PUBLIC_KEY_DIR=/public/.ssh
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:rw
      - ssh:/public/.ssh/
    restart: always
volumes:
  ssh: