apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frp
  name: frp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frp
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frp
    spec:
      containers:
        - image: snowdreamtech/frps
          name: frp
          resources: {}
          volumeMounts:
            - mountPath: /etc/frp/frps.ini
              name: frp-cm0
              subPath: frps.ini
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: frps.ini
                path: frps.ini
            name: frp-cm0
          name: frp-cm0
status: {}

---
apiVersion: v1
data:
  frps.ini: |
    [common]
    bind_port = 54321
    bind_udp_port = 54321
    token = my.frp.token.54321
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: frp
  name: frp-cm0