apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frp-server
  name: frp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frp-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frp-server
    spec:
      containers:
        - image: snowdreamtech/frps
          command:
            - frps
          args:
            - -c
            - /config.toml
          name: frp-server
          resources: {}
          volumeMounts:
            - mountPath: /config.toml
              name: frp-server-cm0
              subPath: config.toml
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.toml
                path: config.toml
            name: frp-server-cm0
          name: frp-server-cm0
status: {}

---
apiVersion: v1
data:
  config.toml: |
    bindPort = ${FRPS_BIND_PORT}

    auth.method = "token"
    auth.token = "${FRPS_TOKEN}"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: frp-server
  name: frp-server-cm0