services:
  xray:
    image: teddysun/xray
    restart: always
    command: xray run -c /etc/xray/config.json
    volumes:
      - ./config.client.json:/etc/xray/config.json
    ports:
      - 127.0.0.1:1080:1080
      - 127.0.0.1:3128:3128