version: '3.9'
services:
  xray:
    image: teddysun/xray
    command: xray run -c /etc/xray/config.json
    volumes:
      - ./config.client.json:/etc/xray/config.json
    ports:
      - 1080:1080
      - 1086:1086
  redsocks:
    image: apiv1/redsocks
    command: localhost 1086
    network_mode: host
    privileged: true
    environment:
      START_FW: 1
    depends_on:
      - xray