apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openldap
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: openldap
    spec:
      containers:
        - env:
            - name: LDAP_ADMIN_PASSWORD
              value: adminpassword
            - name: LDAP_ADMIN_USERNAME
              value: admin
            - name: LDAP_PASSWORDS
              value: password1,password2
            - name: LDAP_USERS
              value: user01,user02
          image: docker.io/bitnami/openldap:2.6
          name: openldap
          ports:
            - containerPort: 1389
            - containerPort: 1636
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/openldap
              name: openldap-data
      restartPolicy: Always
      volumes:
        - name: openldap-data
          persistentVolumeClaim:
            claimName: openldap-data
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: openldap-data
  name: openldap-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  ports:
    - name: "1389"
      port: 1389
      targetPort: 1389
    - name: "1636"
      port: 1636
      targetPort: 1636
  selector:
    io.kompose.service: openldap
status:
  loadBalancer: {}
