services:
  rabbitmq:
    image: rabbitmq:3.13.2-management-alpine
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
volumes:
  rabbitmq:
