name: myenv
services:
  code-server:
    image: apiv1/code-server:daemon
    init: true
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PASSWORD=${PASSWORD:-}
      - HASHED_PASSWORD=${HASHED_PASSWORD:-}
      - PROXY_DOMAIN=${PROXY_DOMAIN:-}
      - CODE_SERVER_BIND_ADDR=${CODE_SERVER_BIND_ADDR:-}
      - CODE_SERVER_ARGS=${CODE_SERVER_ARGS:-}
      - LC_ALL=C.UTF-8
      - CODE_SERVER_WORKSPACE=${CODE_SERVER_WORKSPACE:-${PATH_PREFIX:-}${PWD:-/workdir}}
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
    network_mode: ${NETWORK_MODE:-default}
    volumes:
      - home:/root
      - .:${CODE_SERVER_WORKSPACE:-${PATH_PREFIX:-}${PWD:-/workdir}}
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    tmpfs:
      - /root/.ssh
    ports:
      - ${LISTEN_ADDR:-127.0.0.1:8443}:8443
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  home: