---
services:
  code-server:
    image: apiv1/code-server
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PASSWORD=${PASSWORD:-}
      - HASHED_PASSWORD=${HASHED_PASSWORD:-}
      - SUDO_PASSWORD=${SUDO_PASSWORD:-}
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH:-}
      - PROXY_DOMAIN=${PROXY_DOMAIN:-}
      - TZ=${TZ:-Asia/Shanghai}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE:-/workspace}
    volumes:
      - config:/config
      - ./.workspace:/workspace
    tmpfs:
      - /config/.ssh
    configs:
      - source: .gitconfig
        target: /config/.gitconfig
        mode: 0400
        uid: ${PUID:-1000}
        gid: ${PGID:-1000}
      - source: .bash_aliases
        target: /config/.bash_aliases
        mode: 0400
        uid: ${PUID:-1000}
        gid: ${PGID:-1000}
    ports:
      - ${LISTEN_ADDR:-127.0.0.1:8443}:8443
    restart: unless-stopped
configs:
  .bash_aliases:
    content: |
      export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      test -f ~/.richrc && . ~/.richrc
      load_local_ssh_keys() {
        test -d .ssh && cp -R .ssh/* /config/.ssh/ && chmod -R 400 /config/.ssh/
        test -d .ssh.enc && mkdir -p /config/.ssh.enc/ && cp -R .ssh.enc/* /config/.ssh.enc/
      }
      ssh_keys_decrypt() {
        echo "decrypt: ~/.ssh.enc => ~/.ssh"
        test -d ~/.ssh.enc || return 1
        test -z $$AES_KEY && echo -n 'password: ' && read -s AES_KEY && export AES_KEY && echo
        for item in `ls ~/.ssh.enc`
        do
          cat ~/.ssh.enc/$$item | base64 -d | aes -d > ~/.ssh/$$item
          chmod 400 ~/.ssh/$$item
          echo "decrypt: ~/.ssh.enc/$$item => ~/.ssh/$$item"
        done
      }
      ssh_keys_encrypt() {
        echo "encrypt: ~/.ssh => ~/.ssh.enc"
        test -z $$AES_KEY && echo -n 'password: ' && read -s AES_KEY && export AES_KEY && echo
        mkdir -p ~/.ssh.enc
        for item in `ls ~/.ssh`
        do
          cat ~/.ssh/$$item | aes -e | base64 -w 0 > ~/.ssh.enc/$$item
          echo "encrypt: ~/.ssh/$$item => ~/.ssh.enc/$$item"
        done
      }
      ssh_keys_install () {
        git clone https://github.com/apiv1/.ssh.enc ~/.ssh.enc
      }
      myvim_install () {
        git clone https://github.com/myvim/.vim ~/.vim
      }
      richrc_install () {
        curl -so ~/.richrc https://apiv1.github.io/Shell/richrc
        test -f ~/.richrc && . ~/.richrc
      }
  .gitconfig:
    content: |
      [safe]
        directory = *
      [credential]
        helper = store
      [url "https://kkgithub.com/"]
        insteadOf = https://github.com/
      [url "ssh://git@ssh.github.com:443/"]
        pushInsteadOf = https://github.com/
      [url "ssh://git@ssh.github.com:443/"]
        insteadOf = git@github.com:
volumes:
  config: