name: code-server
services:
  code-server:
    image: apiv1/code-server:daemon
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PASSWORD=${PASSWORD:-}
      - HASHED_PASSWORD=${HASHED_PASSWORD:-}
      - PROXY_DOMAIN=${PROXY_DOMAIN:-}
      - CODE_SERVER_BIND_ADDR=${CODE_SERVER_BIND_ADDR:-}
      - CODE_SERVER_ARGS=${CODE_SERVER_ARGS:-}
      - LC_ALL=C.UTF-8
      - CODE_SERVER_WORKSPACE=${CODE_SERVER_WORKSPACE:-${PATH_PREFIX:-}${PWD}}
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
    network_mode: ${NETWORK_MODE:-default}
    volumes:
      - root:/root
      - .:${CODE_SERVER_WORKSPACE:-${PATH_PREFIX:-}${PWD}}
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    tmpfs:
      - /root/.ssh
    configs:
      - source: .bash_aliases
        target: /root/.bash_aliases
    ports:
      - ${LISTEN_ADDR:-127.0.0.1:8443}:8443
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
configs:
  .bash_aliases:
    content: |
      envrc_install() {
        mkdir -p ~/.envrc.d
        wget -qO ~/.envrc.d/.envrc https://apiv1.github.io/Shell/envrc
        load_envs
      }
      load_envs() {
        local ENV_PATH=~/.envrc.d
        for item in $$(ls -A $${ENV_PATH} 2>/dev/null)
        do
          . "$$ENV_PATH/$$item"
        done
      }
      load_envs
volumes:
  root: