version: '3'
services:
  # docker run -d --restart always --name ss-server -p 1080:1080 shadowsocks/shadowsocks-libev ss-server -s 0.0.0.0 -p 1080 -k ${SS_PASSWD:-passwd} -m chacha20-ietf-poly1305 -u
  ss-server:
    image: shadowsocks/shadowsocks-libev
    restart: always
    command: ss-server -s 0.0.0.0 -p 1080 -k passwd -m chacha20-ietf-poly1305 -u
    ports:
      - "1080:1080"
  # docker run -d --restart always --name ss-local -p 1080:1080 shadowsocks/shadowsocks-libev ss-local -s $SS_SERVER -p ${SS_SERVER_PORT:-1080} -b 0.0.0.0 -l 1080 -k ${SS_PASSWD:-passwd} -m chacha20-ietf-poly1305 -u
  ss-local:
    image: shadowsocks/shadowsocks-libev
    restart: always
    command: ss-local -s $SS_SERVER -p ${SS_SERVER_PORT:-1080} -b 0.0.0.0 -l 1080 -k passwd -m chacha20-ietf-poly1305 -u
    ports:
      - "127.0.0.1:1080:1080"
