---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: xray
  name: xray
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: xray
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: xray
  name: xray
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xray
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/xray-default: "true"
        io.kompose.service: xray
    spec:
      containers:
        - args:
            - xray
            - run
            - -c
            - /etc/xray/config.json
          image: teddysun/xray
          name: xray
          ports:
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/xray
              name: xray-claim0
      restartPolicy: Always
      volumes:
        - name: xray-claim0
          configMap:
            name: xray-claim0
status: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: xray
  name: xray-claim0
data:
  config.json: |
    ${CONFIG_JSON}