version: '3.1'
services:
  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./config:/verdaccio/conf"
      - "storage:/verdaccio/storage"
      - "plugins:/verdaccio/plugins"
volumes:
  storage:
  plugins:
