version: '3'
services:
  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'dev_user'
      MYSQL_PASSWORD: 'pwd_dev_user_555'
      #MYSQL_ROOT_PASSWORD: '_root_pwd_890_'
      MYSQL_ROOT_PASSWORD: 'root'
      LANG: C.UTF-8
    working_dir: /home/app
    ports:
      - 3306:3306
    volumes:
      - .:/home/app
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - ./config/mysql/init.d:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
volumes:
  db:
