services:
  remote-desktop:
    image: apiv1/remote-desktop
    restart: always
    entrypoint: sh
    command: |
      -c "
        groupadd --gid $${PGID} $${USERNAME}
        useradd --shell /bin/bash --uid $${PUID} --gid $${PGID} --password $$(openssl passwd $${PASSWORD}) --create-home --home-dir /home/$${USERNAME} $${USERNAME}
        usermod -aG sudo $${USERNAME}

        /usr/sbin/xrdp-sesman -k
        /usr/sbin/xrdp -k
        rm -rf /run/xrdp/xrdp.pid /run/xrdp/xrdp-sesman.pid

        /usr/sbin/xrdp-sesman
        /usr/sbin/xrdp --nodaemon
      "
    environment:
      USERNAME: ${RDP_USER:-user}
      PASSWORD: ${RDP_PASSWD:-pass}
      PGID: ${RDP_PGID:-2000}
      PUID: ${RDP_PUID:-2000}
    privileged: true
    init: true
    ports:
      - 33389:3389
    volumes:
      - home:/home
volumes:
  home: