if test "$UID" -eq 0; then
  export PROMPT='%F{5}%n%F{1}@%F{4}(%F{3}%W %*%F{4})%F{6}=>%F{2}[%~]%F{3}#%f ' RPROMPT='{%F{3}%?%f}'
else
  export PROMPT='%F{5}%n%F{1}@%F{4}(%F{3}%W %*%F{4})%F{6}=>%F{2}[%~]%F{3}>%f ' RPROMPT='{%F{3}%?%f}'
fi