version: '3.9'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    ports:
      - 8080:8080
    volumes:
      - ./data/applogs:/data/applogs
    environment:
      - "PARAMS=--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"